INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID, AUTHOR_NAME) VALUES ('사내 공지사항 제목 1', '내용입니다. 전체 공지사항이니 모두 확인해주세요.', 'admin', '관리자');
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID, AUTHOR_NAME) VALUES ('주간 회의 일정 공지', '이번 주 회의는 화요일 오전 10시입니다.', 'user01', '홍길동');
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID, AUTHOR_NAME) VALUES ('사무실 환경 정비 공지', '깨끗한 사무실을 위해 다 같이 노력합시다.', 'admin', '관리자');
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID, AUTHOR_NAME) VALUES ('점심 식사 메뉴 변경 안내', '오늘 점심은 부대찌개입니다.', 'user02', '이순신');
INSERT INTO NOTICES (TITLE, CONTENT, AUTHOR_ID, AUTHOR_NAME) VALUES ('월별 보고서 제출 기한 공지', '보고서는 매월 25일까지 제출바랍니다.', 'admin', '관리자');

INSERT INTO TODOS (USER_ID, TITLE, DESCRIPTION, PRIORITY, IS_COMPLETED) VALUES ('user01', '프로젝트 보고서 작성', '이번 달 말까지 제출해야 하는 보고서입니다.', 1, 'N');
INSERT INTO TODOS (USER_ID, TITLE, DESCRIPTION, PRIORITY, IS_COMPLETED) VALUES ('user02', '신규 고객사 미팅 준비', '발표 자료와 계약서 확인하기', 2, 'Y');
INSERT INTO TODOS (USER_ID, TITLE, DESCRIPTION, PRIORITY, IS_COMPLETED) VALUES ('admin', '팀원 평가서 작성', '각 팀원의 성과를 기준으로 평가서 작성', 3, 'N');
INSERT INTO TODOS (USER_ID, TITLE, DESCRIPTION, PRIORITY, IS_COMPLETED) VALUES ('user01', '사내 교육 신청', 'JAVA 교육 온라인 신청', 4, 'Y');
INSERT INTO TODOS (USER_ID, TITLE, DESCRIPTION, PRIORITY, IS_COMPLETED) VALUES ('user02', '서버 점검', '오후 3시에 서버 점검 예정', 1, 'N');

INSERT INTO ATTENDANCE (USER_ID, WORK_DATE, CHECK_IN_TIME, STATUS) VALUES ('user01', SYSDATE, TO_TIMESTAMP('2025-09-01 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'PRESENT');
INSERT INTO ATTENDANCE (USER_ID, WORK_DATE, CHECK_IN_TIME, STATUS) VALUES ('user02', SYSDATE, TO_TIMESTAMP('2025-09-01 09:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'LATE');
INSERT INTO ATTENDANCE (USER_ID, WORK_DATE, CHECK_IN_TIME, STATUS) VALUES ('admin', SYSDATE, TO_TIMESTAMP('2025-09-01 08:50:00', 'YYYY-MM-DD HH24:MI:SS'), 'PRESENT');
INSERT INTO ATTENDANCE (USER_ID, WORK_DATE, CHECK_IN_TIME, STATUS) VALUES ('user01', SYSDATE - 1, TO_TIMESTAMP('2025-08-31 09:05:00', 'YYYY-MM-DD HH24:MI:SS'), 'PRESENT');
INSERT INTO ATTENDANCE (USER_ID, WORK_DATE, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES ('user02', SYSDATE - 2, TO_TIMESTAMP('2025-08-30 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-08-30 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'PRESENT');

INSERT INTO MESSAGES (SENDER_ID, SENDER_NAME, RECEIVER_ID, RECEIVER_NAME, MESSAGE_TYPE, CONTENT, IS_READ) VALUES ('user01', '홍길동', 'admin', '관리자', 'PERSONAL', '오늘 미팅 시간 변경 가능할까요?', 'N');
INSERT INTO MESSAGES (SENDER_ID, SENDER_NAME, RECEIVER_ID, RECEIVER_NAME, MESSAGE_TYPE, CONTENT, IS_READ) VALUES ('admin', '관리자', 'user01', '홍길동', 'PERSONAL', '네, 오후 3시로 변경되었습니다.', 'Y');
INSERT INTO MESSAGES (SENDER_ID, SENDER_NAME, RECEIVER_ID, RECEIVER_NAME, MESSAGE_TYPE, CONTENT, IS_READ) VALUES ('user02', '이순신', 'user01', '홍길동', 'PERSONAL', '점심 같이 먹으실래요?', 'N');
INSERT INTO MESSAGES (SENDER_ID, SENDER_NAME, SENDER_NAME, MESSAGE_TYPE, CONTENT) VALUES ('admin', '관리자', 'admin', '관리자', 'BROADCAST', '사내 공지 확인 바랍니다.');
INSERT INTO MESSAGES (SENDER_ID, SENDER_NAME, SENDER_NAME, RECEIVER_ID, RECEIVER_NAME, MESSAGE_TYPE, CONTENT) VALUES ('user01', '홍길동', '홍길동', 'user02', '이순신', 'PERSONAL', '네 좋아요! 1시에 뵙겠습니다.');

INSERT INTO CALENDAR_EVENTS (USER_ID, TITLE, DESCRIPTION, EVENT_TYPE, START_DATE, END_DATE) VALUES ('admin', '월간 업무 보고', '각 팀의 월간 보고서 발표', 'MEETING', TO_TIMESTAMP('2025-09-05 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-09-05 12:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CALENDAR_EVENTS (USER_ID, TITLE, DESCRIPTION, EVENT_TYPE, START_DATE, END_DATE) VALUES ('user01', '부서 워크숍', '팀 빌딩 및 워크숍 행사', 'COMPANY', TO_TIMESTAMP('2025-09-15 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-09-15 18:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CALENDAR_EVENTS (USER_ID, TITLE, DESCRIPTION, EVENT_TYPE, START_DATE, END_DATE) VALUES ('user02', '개인 약속', '친구와의 저녁 식사', 'PERSONAL', TO_TIMESTAMP('2025-09-02 19:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-09-02 21:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CALENDAR_EVENTS (USER_ID, TITLE, DESCRIPTION, EVENT_TYPE, START_DATE, END_DATE) VALUES ('admin', '추석 연휴', '추석 명절', 'HOLIDAY', TO_TIMESTAMP('2025-09-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-09-19 23:59:59', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CALENDAR_EVENTS (USER_ID, TITLE, DESCRIPTION, EVENT_TYPE, START_DATE, END_DATE) VALUES ('user01', '병원 예약', '오후 2시 치과 검진', 'PERSONAL', TO_TIMESTAMP('2025-09-03 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-09-03 15:00:00', 'YYYY-MM-DD HH24:MI:SS'));

